column_names = [
    "name", "ra", "dec", "flux_1_100_gev", "flux_1_100_gev_error", "detection_significance",
    "semi_major_axis_68", "semi_minor_axis_68", "position_angle_68", "semi_major_axis_95",
    "semi_minor_axis_95", "position_angle_95", "pivot_energy", "energy_flux", "energy_flux_error",
    "pl_flux_density", "pl_flux_density_error", "pl_index", "pl_index_error", "lp_flux_density",
    "lp_flux_density_error", "lp_index", "lp_index_error", "lp_beta", "lp_beta_error",
    "lp_curve_significance", "lp_epeak", "lp_epeak_error", "plec_flux_density",
    "plec_flux_density_error", "plec_index_s", "plec_index_s_error", "plec_exp_factor_s",
    "plec_exp_factor_s_error", "plec_exp_index", "plec_exp_index_error",
    "plec_curve_significance", "plec_epeak", "plec_epeak_error", "npred", "variability_index",
    "frac_variability", "frac_variability_error", "significance_peak", "flux_peak",
    "flux_peak_error", "source_type"
]

unclaimed_columns = ['flux_1_100_gev_error', 'energy_flux_error', 'pl_flux_density_error',
       'pl_index_error', 'lp_flux_density_error', 'lp_index_error',
       'lp_beta_error', 'lp_epeak_error', 'plec_flux_density_error',
       'plec_index_s_error', 'plec_exp_factor_s_error', 'plec_exp_index_error',
       'plec_epeak_error', 'frac_variability_error', 'flux_peak_error']

source_classes = {
    'PSR': 'Pulsar, identified by pulsations',
    'psr': 'Pulsar, no pulsations seen in LAT yet',
    'PWN': 'Pulsar wind nebula',
    'pwn': 'Pulsar wind nebula',
    'SNR': 'Supernova remnant',
    'snr': 'Supernova remnant',
    'SPP': 'Supernova remnant / Pulsar wind nebula',
    'spp': 'Supernova remnant / Pulsar wind nebula',
    'GLC': 'Globular cluster',
    'glc': 'Globular cluster',
    'SFR': 'Star-forming region',
    'sfr': 'Star-forming region',
    'HMB': 'High-mass binary',
    'hmb': 'High-mass binary',
    'LMB': 'Low-mass binary',
    'lmb': 'Low-mass binary',
    'BIN': 'Binary',
    'bin': 'Binary',
    'NOV': 'Nova',
    'nov': 'Nova',
    'BLL': 'BL Lac type of blazar',
    'bll': 'BL Lac type of blazar',
    'FSRQ': 'FSRQ type of blazar',
    'fsrq': 'FSRQ type of blazar',
    'RDG': 'Radio galaxy',
    'rdg': 'Radio galaxy',
    'AGN': 'Non-blazar active galaxy',
    'agn': 'Non-blazar active galaxy',
    'SSRQ': 'Steep spectrum radio quasar',
    'ssrq': 'Steep spectrum radio quasar',
    'CSS': 'Compact Steep Spectrum radio source',
    'css': 'Compact Steep Spectrum radio source',
    'BCU': 'Blazar candidate of uncertain type',
    'bcu': 'Blazar candidate of uncertain type',
    'NLSY1': 'Narrow-line Seyfert 1',
    'nlsy1': 'Narrow-line Seyfert 1',
    'SEY': 'Seyfert galaxy',
    'sey': 'Seyfert galaxy',
    'SBG': 'Starburst galaxy',
    'sbg': 'Starburst galaxy',
    'GAL': 'Normal galaxy (or part)',
    'gal': 'Normal galaxy (or part)',
    'UNK': 'Unknown',
    'unk': 'Unknown',
    'MSP': 'Millisecond pulsar',
    'msp': 'Millisecond pulsar',
    'GC': 'GC?',
    'gc': 'gc?',
}

replacements = {
        'unk': 'unknown',
        'bll': 'blazar', 'BLL': 'blazar', 'bcu': 'blazar', 'BCU': 'blazar', 'fsrq': 'blazar', 'FSRQ': 'blazar',
        'psr': 'pulsar', 'PSR': 'pulsar'
    }